### ISSUE TITLE
Type hints for recordsets

### ISSUE THREAD

**Issue by trinhanhngoc** [odoo-ide/vscode-odoo#23]
https://odoo-ide.com/blog/news-1/pycharm-odoo-2022-6-10

![image](https://github.com/odoo-ide/vscode-odoo/assets/11208291/039170d5-5a6f-494c-bcfd-6f4b8a368661)

**Comment by trinhanhngoc** [comment]
-

**Comment by gustitammam** [comment]
Hello @trinhanhngoc,

I'm not entirely sure if this is the appropriate place for me to add my comment or create a new issue, but it seems to be related to the issue I've come across here, so I'll go ahead and post my comment in this issue.

I've been using PyCharm with the Odoo IDE plugin, and I'm currently experimenting with VSCode along with the Odoo IDE. I've noticed a difference in behavior when I attempt to inherit a class method. Specifically, when I start typing, there's an autocomplete feature for the function name. However, when I accept this autocomplete suggestion, the inherited method includes parameter names within its definition.

![image](https://github.com/odoo-ide/vscode-odoo/assets/11481845/05d454c1-c4ff-4d05-9710-ee00996f8d4e)

![image](https://github.com/odoo-ide/vscode-odoo/assets/11481845/7cff7118-1d4e-435b-8483-afd70a8538ef)


I'm curious whether this behavior is intentional or if there's a way to disable it, allowing the parameter names to appear as they typically do in PyCharm.

**Current Behavior:**
```
def search_read(self, domain: list | None = ..., fields: list[str] | None = ..., offset: int = ..., limit: int | None = ..., order: str | None = ..., **read_kwargs: str) -> list[dict[str, Any]]:
    return super().search_read(domain, fields, offset, limit, order, **read_kwargs)
```

**Expected Behavior:**
```
def search_read(self, domain=None, fields=None, offset=0, limit=None, order=None, **read_kwargs):
    return super().search_read(domain, fields, offset, limit, order, **read_kwargs)
```

**VSCode version:** 1.83.1
**Odoo IDE version:** v0.11.1 

Your insights and guidance on resolving this issue would be greatly appreciated. Thank you!
