### ISSUE TITLE
Issue detecting odoo libraries

### ISSUE THREAD

**Issue by ymolinar** [odoo-ide/vscode-odoo#26]
I have installed the module following the steps in the documentation and I can't get it to detect the Odoo libraries. The odoo.addons... if they work correctly, the problem is only with the Odoo base libraries
This is my project folder organization:
![project-folder-organization](https://github.com/odoo-ide/vscode-odoo/assets/8480924/0fc13178-5088-43e6-8bab-bcf3cd201080)

This are the issues
![without-odoo odoo](https://github.com/odoo-ide/vscode-odoo/assets/8480924/c6547607-b160-49c1-a6a6-42c04a5ee0f7)

But if i use odoo.odoo works great.
![with-odoo odoo](https://github.com/odoo-ide/vscode-odoo/assets/8480924/e02e68b1-bf62-4d54-b6f4-c8e2bee8cd4a)

**Comment by trinhanhngoc** [comment]
Hi @ymolinar. Your Odoo workspace needs to be configured a bit for it to work. Because the odoo source code folder is not the root folder of your workspace (it is currently a sub-folder of the root folder, besides other folders such as addons, bin, build,...), the Python language server cannot resolve imports from odoo without additional configuration. To make it work, you can create a `pyrightconfig.json` in the root folder of your workspace with something like the following sample:

```
{
    "extraPaths": ["odoo"]
}
```
Note: `odoo` is the relative path to the odoo source code in your workspace.

Also, you should not put the `odoo-stubs` folder inside the odoo source code folder. You can put `odoo-stubs` outside your workspace and set the relative path to it in `pyrightconfig.json` like:

```
{
    "extraPaths": ["odoo"],
    "stubPath": "../relative/path/to/odoo-stubs"
}
```

I simulated your workspace structure and here are my results:

<img width="1624" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/11208291/9fda7a7d-7cda-411c-ad26-8f6c99925126">

<img width="1624" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/11208291/c6f52746-0952-4fab-8e6a-8eb879fe18a6">

You can learn more about import resolution here: https://microsoft.github.io/pyright/#/import-resolution

**Comment by ymolinar** [comment]
Work's like a charm.
